In [33]:
import numpy as np

## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [34]:
n = 9
a = np.arange(n - 1, -1, -1)
print(a)

[8 7 6 5 4 3 2 1 0]


## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали

In [35]:
d = np.diag(a, k=0)
print(d)
print(sum(np.diagonal(d)))

[[8 0 0 0 0 0 0 0 0]
 [0 7 0 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]]
36


## Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [36]:
u = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
v = np.array([4, 12, -3])
xyz = np.linalg.solve(u, v)
print(xyz)

[ 0.46666667  3.84444444 -5.55555556]


## Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [37]:
# исходные данные
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 2, 2, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4],
        [0, 1, 3, 0, 0, 0],
        [2, 1, 0, 2, 2, 2]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

# косинус угла между векторами a и b
def cosine(a, b):
    len_a = np.linalg.norm(a)
    len_b = np.linalg.norm(b)
# необходимо исключить 0 в знаменателе
    if len_a != 0 and len_b != 0:
        return np.dot(a, b) / (len_a * len_b)
    else:
# 0 в знаменателе означает, что кто-то из сравниваемых пользователей (или оба) ничего не покупал и
# считать его похожим на другого не имеет смысла -> возвращаем 0
        return 0

# вектор косинусных метрик
cos_metric = np.array([cosine(next_user_stats, user_stats) for user_stats in users_stats])
# максимальное значение метрики
max_cos_metric = np.max(cos_metric)
# проверяем существует ли пользователь с метрикой схожести, отличной от 0
# отрицательные значения не проверяем, так как по условию задачи измерения векторов либо нулевые либо имеют положительное направление
if max_cos_metric !=0:
    # !ЕСТЬ! 
    # Возможно, пользователей с одинаковой максимальной метрикой несколько, 
    # создаем массив индексов максимально похожих пользователей
    
    max_indexes = [i for i, max_ in enumerate(cos_metric) if max_ == max_cos_metric]
    print(f'Вектор косинусных метрик: {list(format(cm, ".2f") for cm in cos_metric)}')
    print(f'Вектор покупок нового пользователя: ', list(next_user_stats))
    print(f'Вектор самого похожего пользователя: {[list(users_stats[i]) for i in max_indexes]}\n', 
          f'          Значение меры похожести: {max_cos_metric :0.2f}',
          f'Индекс пользователя: {max_indexes}' 
         )
    # Но, если нужно найти только одного пользователя, можно использовать метод np.argmax()
else:
    # Либо все векторы имеют длину 0, либо новый пользователь с нулевой длиной вектора
    print('Сходства не найдено!!!')
    

Вектор косинусных метрик: ['0.20', '0.85', '0.40', '0.79', '0.40', '0.00', '0.00', '0.95', '0.00', '0.00', '0.99', '0.11']
Вектор покупок нового пользователя:  [0, 1, 2, 0, 0, 0]
Вектор самого похожего пользователя: [[0, 1, 3, 0, 0, 0]]
           Значение меры похожести: 0.99 Индекс пользователя: [10]
